import 'package:flutter/material.dart';

/// The Viby brand mark (the swirl glyph), for in-app use.
///
/// One widget so the mark is never hand-placed twice. The asset is the glyph as
/// a white silhouette on transparency (generated by `tools/gen_icons.py` from
/// the same master as the launcher icon), so it can be tinted to any scheme
/// colour — pass [color], defaulting to `onSurface`.
class VibyMark extends StatelessWidget {
  const VibyMark({super.key, this.size = 24, this.color});

  final double size;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return Image.asset(
      'assets/brand/viby_mark.png',
      width: size,
      height: size,
      color: color ?? Theme.of(context).colorScheme.onSurface,
      // The asset is a silhouette: tint its opaque pixels, keep its alpha.
      colorBlendMode: BlendMode.srcIn,
      filterQuality: FilterQuality.medium,
    );
  }
}
